kafkaconsumer_bootstrap: kafka:9092
kafkaconsumer_topics: gat1400,transmit
kafkaconsumer_groupId: statistics_1
kafkaconsumer_fromEarliestOffset: true
kafkaconsumer_batchSize: 1000
kafkaconsumer_batchDelay: 5000
redis:
  addr: 192.168.100.100:16379
center:
  wsPort: 18080
  wsPath: /exchange/ws/{namespace}/{sid}